apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rediscruds.shield.com
spec:
  group: shield.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                port:
                  type: integer
                  minimum: 1
                  maximum: 65535
                replicas:
                  type: integer
                  minimum: 1
              required:
                - port
                - replicas
  scope: Namespaced
  names:
    plural: rediscruds
    singular: rediscrud
    kind: RedisCrud
    shortNames:
      - rc
  preserveUnknownFields: false

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: slacknotificators.shield.com
spec:
  group: shield.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
  scope: Namespaced
  names:
    plural: slacknotificators
    singular: slacknotificator
    kind: SlackNotificator
    shortNames:
      - sn
  preserveUnknownFields: false
