apiVersion: apps/v1
kind: Deployment
metadata:
  name: slacknotifier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slacknotifier-deployment
  template:
    metadata:
      labels:
        app: slacknotifier-deployment
    spec:
      containers:
        - name: slacknotifier-deployment
          image: jin105/slack-notificator
          env:
            - name: PORT
              value: "4568"
            - name: SLACK_CHANNEL
              value: "<CHANNEL>"
            - name: SLACK_TOKEN
              value: "<TOKEN>"
---
apiVersion: v1
kind: Service
metadata:
  name: slacknotifier-service
spec:
  ports:
    - protocol: TCP
      port: 4568
  selector:
    app: slacknotifier-service
